name: Criar Release Automático

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    # Configuração atualizada para o Java 21
    - name: Configurar o JDK Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Compilar projeto com Maven
      run: mvn clean package -DskipTests

    - name: Criar GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: target/*.jar